### ISSUE TITLE
Workflow not working: ERROR: Bootstrap Docs[Script Filter] Code 127: /bin/bash: php: command not found

### ISSUE THREAD

**Issue by tgermer** [jerryklimcik/alfred-bootstrap-docs#1]
Hi,

Unfortunately, the workflow does not work.
The following errors are thrown:

```
[14:26:16.549] Bootstrap Docs[Script Filter] Queuing argument 'n'
[14:26:16.629] Bootstrap Docs[Script Filter] Script with argv '(null)' finished
[14:26:16.631] ERROR: Bootstrap Docs[Script Filter] Code 127: Exited with error code but no message
[14:26:16.717] Bootstrap Docs[Script Filter] Queuing argument 'na'
[14:26:16.730] Bootstrap Docs[Script Filter] Script with argv '(null)' finished
[14:26:16.732] ERROR: Bootstrap Docs[Script Filter] Code 127: Exited with error code but no message
[14:26:16.964] Bootstrap Docs[Script Filter] Queuing argument 'nav'
[14:26:17.065] Bootstrap Docs[Script Filter] Script with argv '(null)' finished
[14:26:17.067] ERROR: Bootstrap Docs[Script Filter] Code 127: Exited with error code but no message
[14:26:19.226] Bootstrap Docs[Script Filter] Queuing argument 'na'
[14:26:19.278] Bootstrap Docs[Script Filter] Script with argv '(null)' finished
[14:26:19.283] ERROR: Bootstrap Docs[Script Filter] Code 127: Exited with error code but no message
[14:26:19.389] Bootstrap Docs[Script Filter] Queuing argument 'n'
[14:26:19.484] Bootstrap Docs[Script Filter] Script with argv '(null)' finished
[14:26:19.491] ERROR: Bootstrap Docs[Script Filter] Code 127: /bin/bash: php: command not found
[14:26:19.894] Bootstrap Docs[Script Filter] Queuing argument 'm'
[14:26:19.999] Bootstrap Docs[Script Filter] Script with argv '(null)' finished
[14:26:20.010] ERROR: Bootstrap Docs[Script Filter] Code 127: Exited with error code but no message
[14:26:20.078] Bootstrap Docs[Script Filter] Queuing argument 'mo'
[14:26:20.116] Bootstrap Docs[Script Filter] Script with argv '(null)' finished
[14:26:20.128] ERROR: Bootstrap Docs[Script Filter] Code 127: /bin/bash: php: command not found
[14:26:20.195] Bootstrap Docs[Script Filter] Queuing argument 'mod'
[14:26:20.297] Bootstrap Docs[Script Filter] Script with argv '(null)' finished
[14:26:20.308] ERROR: Bootstrap Docs[Script Filter] Code 127: /bin/bash: php: command not found
[14:26:20.336] Bootstrap Docs[Script Filter] Queuing argument 'moda'
[14:26:20.368] Bootstrap Docs[Script Filter] Script with argv '(null)' finished
[14:26:20.384] ERROR: Bootstrap Docs[Script Filter] Code 127: /bin/bash: php: command not found
[14:26:20.446] Bootstrap Docs[Script Filter] Queuing argument 'modal'
[14:26:20.540] Bootstrap Docs[Script Filter] Script with argv '(null)' finished
[14:26:20.553] ERROR: Bootstrap Docs[Script Filter] Code 127: /bin/bash: php: command not found
```

Do you think you can help?
Thank you and greetings

Tristan

**Comment by jerryklimcik** [comment]
Hi @tgermer , thank you for reporting it. Fixed in new version, please [download new version](https://github.com/jerryklimcik/alfred-bootstrap-docs/releases/download/0.1.1/Bootstrap.Docs.alfredworkflow)

**Comment by tgermer** [comment]
Thank you, but it is still not working for me.
Version 0.1.1

<img width="796" alt="image" src="https://user-images.githubusercontent.com/21098461/145604352-2de92336-2cc7-40ce-9067-a1f39a37ef8d.png">
